"""Validation logic for pages and site structure."""

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .config import Config
    from .page import Page


@dataclass
class ValidationError:
    """Represents a validation error or warning."""

    path: Path
    message: str
    is_fatal: bool = True


@dataclass
class ValidationResult:
    """Result of validating a page or the entire site."""

    errors: list[ValidationError] = field(default_factory=list)
    warnings: list[ValidationError] = field(default_factory=list)

    @property
    def has_fatal_errors(self) -> bool:
        """Check if there are any fatal errors."""
        return any(e.is_fatal for e in self.errors)

    def merge(self, other: "ValidationResult") -> None:
        """Merge another validation result into this one."""
        self.errors.extend(other.errors)
        self.warnings.extend(other.warnings)


class PageValidator:
    """Validates individual pages."""

    def __init__(self, config: "Config") -> None:
        self.config = config

    def validate(self, page: "Page") -> ValidationResult:
        """Validate a single page."""
        result = ValidationResult()

        # Required: title
        if not page.title:
            result.errors.append(
                ValidationError(
                    page.source_path,
                    "Missing required frontmatter field: title",
                    is_fatal=True,
                )
            )

        # Check layout exists
        if page.layout:
            layout_path = self.config.layout_path / page.layout
            if not layout_path.exists():
                result.errors.append(
                    ValidationError(
                        page.source_path,
                        f"Layout file does not exist: {page.layout}",
                        is_fatal=True,
                    )
                )

        # Check image exists (if specified)
        if page.image:
            image_path = self.config.files_path / page.image
            if not image_path.exists():
                result.errors.append(
                    ValidationError(
                        page.source_path,
                        f"Image file does not exist: {page.image}",
                        is_fatal=True,
                    )
                )

        # Warnings for missing optional fields
        if not page.description:
            result.warnings.append(
                ValidationError(
                    page.source_path,
                    "Missing recommended frontmatter field: description",
                    is_fatal=False,
                )
            )

        if not page.image:
            result.warnings.append(
                ValidationError(
                    page.source_path,
                    "Missing recommended frontmatter field: image",
                    is_fatal=False,
                )
            )

        return result


class SiteValidator:
    """Validates the entire site for cross-page issues."""

    def validate_no_duplicate_outputs(
        self, pages: list["Page"]
    ) -> ValidationResult:
        """Ensure no two Markdown files generate the same output path."""
        result = ValidationResult()
        seen: dict[Path, Path] = {}  # output_path -> source_path

        for page in pages:
            if page.output_path in seen:
                result.errors.append(
                    ValidationError(
                        page.source_path,
                        f"Duplicate output path: {page.output_path} "
                        f"(also generated by {seen[page.output_path]})",
                        is_fatal=True,
                    )
                )
            else:
                seen[page.output_path] = page.source_path

        return result
